spring.application.name=ExpenseTracker


# Postgres Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=${postgres_password}
